### ISSUE TITLE
当IP输入框的四个框都输入同一个1位数时会出现值错误

### ISSUE THREAD

**Issue by ZooMze** [Linkontoask/v-easy-components#66]
初始值为[]
分别输入1.1.1.1
预计结果[1,1,1,1]
实际结果[1] (length同样为1)
2位数 3位数连续输入没有问题

**Comment by Linkontoask** [comment]
谢谢反馈。确实有这个问题，我会在下次提交中修复。目前正在支持vue-next，可能修复不及时。
